arb-dir: lib/l10n
template-arb-file: app_zh.arb
output-localization-file: app_localizations.dart

synthetic-package: false
output-dir: lib/l10n/gen
output-class: AppLocalizations
nullable-getter: false
untranslated-messages-file: desiredFileName.txt
