name: aiflutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  logger: ^2.5.0
  flutter_native_splash: ^2.4.4
  flutter_phoenix: ^1.1.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqflite_common_ffi_web: ^0.4.5+4
  auto_size_text: ^3.0.0
  markdown_widget: ^2.3.2+6
  loading_more_list: ^7.1.0
  flutter_tts: ^4.2.2
  flutter_markdown: ^0.7.6+2
  markdown: ^7.3.0
  path: ^1.9.0
  custom_sliding_segmented_control: ^1.8.5
  flex_color_picker: ^3.7.0
  qr_flutter: ^4.1.0
  camerawesome: ^2.3.0
  intl: ^0.20.2
  animated_text_kit: ^4.2.3
  animations: ^2.0.11
  loading_animation_widget: ^1.3.0
  flutter_slidable: ^4.0.0
  flip_card: ^0.7.0
  circular_countdown_timer: ^0.2.4
  uuid: ^4.5.1
  settings_ui: ^2.0.2
  clipboard: ^0.1.3
  flutter_math_fork: ^0.7.3
  web_socket_channel: ^3.0.2
  ve_sdk_flutter: ^0.15.0
  open_filex: ^4.7.0
  cross_file: ^0.3.4+2
  path_provider: ^2.1.5
  ruby_text: ^3.0.3
  lpinyin: ^2.0.3
  pinyin: ^3.3.0
  azlistview_plus: ^3.0.0
  fl_chart: ^0.66.2
  graphic: ^2.5.1
  nine_grid_view: ^2.0.0
  flutter_gallery_assets: ^1.0.2
  flutter_box_transform: ^0.4.7
  hyper_effects: ^0.3.0
  audio_waveforms: ^1.3.0
  flutter_settings_ui: ^3.0.1
  loader_overlay: ^5.0.0
  flutter_client_sse: ^2.0.3
  eventflux: ^2.2.1
  dismissible_page: ^1.0.2
  # new
  flutter_riverpod: ^2.6.1
  event_bus: ^2.0.1
  get: ^4.7.2
  image_picker: ^1.1.2
  flutter_swiper_null_safety_flutter3: ^4.0.3
  tdesign_flutter: ^0.1.9
  flutter_liquid_swipe: ^0.0.1
  liquid_swipe: ^3.1.0
  toastification: ^3.0.2
  file_picker: ^10.1.9
  flutter_easyloading: ^3.0.5
  bitsdojo_window: ^0.1.6
  animated_toggle_switch: ^0.8.5

dependency_overrides:
  tdesign_flutter:
    path: ../library/tdesign-flutter/tdesign-component

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/bridge.png
    - assets/flutter.png
    - assets/app.png
    - assets/welcome.png
    - assets/images/
    - packages/flutter_gallery_assets/people/ali_landscape.png
    - packages/flutter_gallery_assets/people/square/ali.png
    - packages/flutter_gallery_assets/people/square/peter.png
    - packages/flutter_gallery_assets/people/square/sandra.png
    - packages/flutter_gallery_assets/people/square/stella.png
    - packages/flutter_gallery_assets/people/square/trevor.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png

flutter_native_splash:
  image: assets/flutter.png
  color: "#FFFFFF"
  android_12:
    image: assets/flutter.png
    icon_background_color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/flutter.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/flutter.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/flutter.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/flutter.png"
